[module]
  [module.hugoVersion]
    extended = true
    min = '0.90.0'

baseurl = "https://example.com/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = true
  centerTheme = true

[languages]
  [languages.en]
    title = "La stanza buia"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "La stanza buia"
      logoHomeLink = "/"

    
